# Machine Learning Assignment 

#### Assignment for joining internship at Tutree

#### Q. 1 Explain dimension reduction in machine learning.

#### Ans. 
        Dimension reduction refers to techniques that reduce number of independent variables. In machine learning dimension reduction helps in following ways
      1. To reduce computation and minimizing complexity model.
      2. Some machine learning alogrithms do not work well when data has large dimension.
      3. Having large dimension in data that leads to problem in data visualizing. 

#### Q.2 How can you handle duplicate values in a dataset for a variable in Python using pandas?

    Here I am using a dataset where following are columns: 
        1. GameID
        2. GameName
        3. Purchase or Play

#### Required library  

In [19]:
import pandas as pd
import seaborn as sns

#### Data importing 

In [3]:
Game_df = pd.read_csv('Games.csv')

In [13]:
Game_df.columns = ['ID', 'GameName','Purchase or Play']

In [14]:
Game_df.head()

ID                    GameName Purchase or Play
0  151603712  The Elder Scrolls V Skyrim             play
1  151603712                   Fallout 4         purchase
2  151603712                   Fallout 4             play
3  151603712                       Spore         purchase
4  151603712                       Spore             play

In [15]:
Game_df.shape

(199999, 3)

This dataset having total 199,999 rows and 3 columns

In [16]:
Game_df.duplicated().sum()

719

This data has total 719 duplicate values

In [29]:
Game_df.drop_duplicates(inplace= True)

This remove all 719 duplicate rows for dataset

In [30]:
print('Duplicate values in ID :',Game_df['ID'].duplicated().sum())
print('Duplicate values in Game Name :',Game_df['GameName'].duplicated().sum())
print('Duplicate values in Purchase or Play :',Game_df['Purchase or Play'].duplicated().sum())

Duplicate values in ID : 186887
Duplicate values in Game Name : 194125
Duplicate values in Purchase or Play : 199278


Here, we remove all dupilcate rows and keep only one record form them.

In [31]:
Game_df['ID'].drop_duplicates(inplace= True)
Game_df['GameName'].drop_duplicates(inplace= True)
Game_df['Purchase or Play'].drop_duplicates(inplace= True)

In [32]:
print('Duplicate values in ID :',Game_df['ID'].duplicated().sum())
print('Duplicate values in Game Name :',Game_df['GameName'].duplicated().sum())
print('Duplicate values in Purchase or Play :',Game_df['Purchase or Play'].duplicated().sum())

Duplicate values in ID : 0
Duplicate values in Game Name : 0
Duplicate values in Purchase or Play : 0
